ALTER TABLE sys_user ADD COLUMN post_id BIGINT AFTER org_id;
ALTER TABLE sys_user ADD COLUMN eoa_id VARCHAR(50) AFTER post_id;
ALTER TABLE sys_user ADD COLUMN usap_account VARCHAR(50) AFTER eoa_id;

CREATE TABLE IF NOT EXISTS sys_post (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  post_code VARCHAR(64) NOT NULL UNIQUE,
  post_name VARCHAR(50) NOT NULL,
  post_sort INT DEFAULT 0,
  status TINYINT DEFAULT 1,
  deleted TINYINT DEFAULT 0,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_post_code (post_code),
  INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
